apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ .Values.deployColor }}
  labels:
    app: finacplus
    color: {{ .Values.deployColor }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finacplus
      color: {{ .Values.deployColor }}
  template:
    metadata:
      labels:
        app: finacplus
        color: {{ .Values.deployColor }}
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: finacplus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: COLOR
              value: "{{ .Values.deployColor }}"
          ports:
            - containerPort: 3000
