apiVersion: v1
kind: Service
metadata:
  name: finacplus-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: finacplus
    color: {{ .Values.liveColor }}
